export {
  createDraft,
  getDraftById,
  getDraftCustomerReferenceById,
  getDraftExporterDetailById,
  getDraftImporterDetailById,
  getDraftWasteDescriptionById,
  getDraftWasteQuantityById,
  getDrafts,
  setDraftCustomerReferenceById,
  setDraftExporterDetailById,
  setDraftImporterDetailById,
  setDraftWasteDescriptionById,
  setDraftWasteQuantityById,
} from './dto';

export type {
  CreateDraftRequest,
  CreateDraftResponse,
  DraftSubmission,
  DraftSubmissionSummary,
  GetDraftByIdRequest,
  GetDraftByIdResponse,
  GetDraftCustomerReferenceByIdRequest,
  GetDraftCustomerReferenceByIdResponse,
  GetDraftExporterDetailByIdRequest,
  GetDraftExporterDetailByIdResponse,
  GetDraftImporterDetailByIdRequest,
  GetDraftImporterDetailByIdResponse,
  GetDraftWasteDescriptionByIdRequest,
  GetDraftWasteDescriptionByIdResponse,
  GetDraftWasteQuantityByIdRequest,
  GetDraftWasteQuantityByIdResponse,
  GetDraftsRequest,
  GetDraftsResponse,
  SetDraftCustomerReferenceByIdRequest,
  SetDraftCustomerReferenceByIdResponse,
  SetDraftExporterDetailByIdRequest,
  SetDraftExporterDetailByIdResponse,
  SetDraftImporterDetailByIdRequest,
  SetDraftImporterDetailByIdResponse,
  SetDraftWasteDescriptionByIdRequest,
  SetDraftWasteDescriptionByIdResponse,
  SetDraftWasteQuantityByIdRequest,
  SetDraftWasteQuantityByIdResponse,
} from './dto';

export * as schema from './schema';
