# frozen_string_literal: true
source 'https://rubygems.org'

ruby '~> 3.0'

gem 'activesupport', '~>6.1.4.1'
gem 'capybara', '~> 3.37.0'
gem 'capybara-screenshot', '~> 1.0.25'
gem 'cucumber', '~> 8.0.0'
gem 'cucumber-core', '~> 11.0.0'
gem 'cuke_modeler', '~> 3.17.0'
gem 'faker', '~> 2.17.0'
gem 'parallel_tests', '~> 3.7.0'
gem 'rspec', '~> 3.10.0'
gem 'rubocop', '~> 1.24.1'
gem 'selenium-webdriver', '4.1.0'
gem 'webdrivers', '~> 5.3.0'
gem 'report_builder', '1.8'
gem 'logging', '~>2.3.0'
gem 'axe-core-cucumber'
gem 'axe-core-capybara'
gem 'browserstack-local'



