export {
  getWasteCodes,
  getEWCCodes,
  getCountries,
  getRecoveryCodes,
  getDisposalCodes,
  getHazardousCodes,
  getPops,
  getLocalAuthorities,
  getSICCodes,
  createWasteCodes,
  createEWCCodes,
  createCountries,
  createRecoveryCodes,
  createDisposalCodes,
  createHazardousCodes,
  createPops,
  createSICCodes,
} from './reference-data.dto';

export type {
  WasteCode,
  WasteCodeType,
  Country,
  RecoveryCode,
  Pop,
  LocalAuthority,
  SICCode,
  GetWasteCodesResponse,
  GetEWCCodesResponse,
  GetEWCCodesRequest,
  GetCountriesResponse,
  GetCountriesRequest,
  GetRecoveryCodesResponse,
  GetDisposalCodesResponse,
  GetHazardousCodesResponse,
  GetPopsResponse,
  GetLocalAuthoritiesResponse,
  GetSICCodesResponse,
  CreateWasteCodesRequest,
  CreateWasteCodesResponse,
  CreateEWCCodesRequest,
  CreateEWCCodesResponse,
  CreateCountriesRequest,
  CreateCountriesResponse,
  CreateRecoveryCodesRequest,
  CreateRecoveryCodesResponse,
  CreateDisposalCodesRequest,
  CreateDisposalCodesResponse,
  CreateHazardousCodesRequest,
  CreateHazardousCodesResponse,
  CreatePopsRequest,
  CreatePopsResponse,
  CreateSICCodesRequest,
  CreateSICCodesResponse,
} from './reference-data.dto';

export * as schema from './reference-data.schema';
